-- Check all tables
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

SELECT TOP 10 * FROM Customerss;

SELECT COUNT(*) AS Total_Rows
FROM Customerss;

SELECT 
    COLUMN_NAME,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Customerss'
ORDER BY ORDINAL_POSITION;

